### PR TITLE
Add LocationWrapper to allow FakeLocations on other servers

### PR DESCRIPTION
**Pull request by Maxopoly**
@rourke750

### CODE REVIEW

**Comment by rourke750** [comment]
looks good.

**Comment by ProgrammerDan** [comment]
Did there need to be a check for LocationWrapper to prevent its storage?

**Comment by Maxopoly** [comment]
Well, the portal location stuff is only stored when it's created, so technically it should always have the right world, but I also changed this:

https://github.com/Civcraft/BetterShards/pull/50/files#diff-c8570924a48dd978b53bd9442d91b16cR218

to ensure that it's always using the right world.

**Comment by ProgrammerDan** [comment]
Right on. Looks good.

**Pull request merged**
