### PR TITLE
Untag players before connecting them to a new server

### PR DESCRIPTION
**Pull request by idoash4**

### CODE REVIEW

**Comment by rourke750** [comment]
Lol can we revert this

**Comment by rourke750** [comment]
We don't want players being able to teleport if combat tagged. They must be untagged elseware if we want them to be able to connect.

**Comment by rourke750** [comment]
Lol ignore me I'm stupid

**Comment by Maxopoly** [comment]
It still prevents that for portals, this was for something else, @BlackXnt knows more

**Comment by rourke750** [comment]
I messed up on looking at the pull. I saw the untag and thought that was
replacing the return statement. Just ignore everything I've said.

**Pull request merged**
