### PR TITLE
Fix portal behavior

### PR DESCRIPTION
**Pull request by Maxopoly**
So apparently Material.isSolid returns true for lava and water? Interesting. To fix that portal spawning will now respect the same material ignore list as random spawning. Additionally portal spawning will now create a valid spawning location on bedrock if there is none. If there is no bedrock, a piece of stone to stand on will be spawned

### CODE REVIEW

**Comment by Maxopoly** [comment]
Also adresses https://github.com/Civcraft/BetterShards/issues/92 and the same issue with pistons

**Comment by ProgrammerDan** [comment]
@Maxopoly I rebased and forced this push so it'll be out of sync with your local, but clean merge against current master.

Anything missing from here? Is this tested?

**Comment by Maxopoly** [comment]
Oh I thought this was already online. Havent gotten a chance to test it, but it's fairly straight forward, so it should be fine

**Comment by Maxopoly** [comment]
lmao I was telling everyone that the spawning issues were fixed, but we never merged this

**Pull request merged**
