### PR TITLE
Adding listeners for post-execution of stop

### PR DESCRIPTION
**Pull request by ProgrammerDan**
First stab at forcing player data save on server shutdown, as the standard MC process apparently skips some players sometimes.

### CODE REVIEW

**Comment by rourke750** [comment]
Increment pom then merge.

**Comment by Maxopoly** [comment]
At least I'm not the only one forgetting that.

**Comment by ProgrammerDan** [comment]
Yeah it's because I did it inline. Only one file change per commit, fml.

**Comment by Maxopoly** [comment]
http://build.civcraft.co/job/BetterShards-master/116/console

**Comment by ProgrammerDan** [comment]
Ah had this actually been mergetested locally? Mentioned in OP that I did not.

**Comment by ProgrammerDan** [comment]
Eh fixing locally, expect a new pull shortly.

**Comment by rourke750** [comment]
Woops https://github.com/Civcraft/BetterShards/pull/14/files#diff-3eedc7be59ee92f3ddc8bb66277db536R27

**Comment by Maxopoly** [comment]
Yeah, but that's not the issue I already fixed that

https://github.com/Civcraft/BetterShards/commit/508e9ad848dcebeb5d2ed7d808a6b1f3bc574dca

**Comment by ProgrammerDan** [comment]
new build seems to have solved it.

**Pull request merged**
