### PR TITLE
added shard command

### PR DESCRIPTION
**Pull request by rourke750**

### CODE REVIEW

**Comment by rourke750** [comment]
@erocs

**Comment by rourke750** [comment]
@ProgrammerDan 
This should be fine.

**Comment by ProgrammerDan** [comment]
Yeah it seems it was actually online and I replaced it (woops). Should be totally safe to merge, I actually used it last night, bravo.

Once you fix the conflict (probably pom.xml) go ahead and merge.

**Comment by rourke750** [comment]
How was it online? I never merged it?

**Comment by ProgrammerDan** [comment]
Nevermind. Apparently /server just prints this same list basically.

**Comment by ProgrammerDan** [comment]
Any reason you haven't rebased and merged yet @rourke750 ? :D

**Comment by rourke750** [comment]
Cause I think I did it locally. Lol I'll push when I get the chance.

**Pull request merged**
