### PR TITLE
Let players update their bed at any time of the day

### PR DESCRIPTION
**Pull request by ghost**
It's really frustrating to have to wait for night time to set your bed location.

This PR changes the set-bed method to use the PlayerInteractEvent instead of PlayerBedEnterEvent so that simply right-clicking on a bed block will update the bed location even if it's night time.

### CODE REVIEW

**Comment by Maxopoly** [comment]
Hmm, not sure whether we want this.

**Comment by ghost** [comment]
Your call, I've been using this approach myself and it works well. 
Having to wait until night time is pretty pointless.

**Comment by ProgrammerDan** [comment]
I'm not opposed to it. I can take a nap any time during the day IRL; and the "only nighttime" mechanic only makes sense for singleplayer, as it's a way to skip time and avoid mobspawn. That doesn't apply here.

**Comment by rourke750** [comment]
I'm for the pull.

**Comment by Maxopoly** [comment]
Alright then

**Pull request merged**
