### PR TITLE
Fixed updateVersion to use table bettershards_version

### PR DESCRIPTION
**Pull request by Scuwr**
Fixed updateVersion to use table bettershards_version instead of old db_version. Not compiled or tested. Maven has many dependencies that cannot be resolved.

```
[INFO] 66 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:54 min
[INFO] Finished at: 2016-02-01T10:50:21-07:00
[INFO] Final Memory: 19M/126M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project BetterShards: Compilation failure: Compilation failure:
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/BetterShardsPlugin.java:[19,36] package net.minecraft.server.v1_8_R3 does not exist
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/BetterShardsPlugin.java:[20,36] package net.minecraft.server.v1_8_R3 does not exist
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/BetterShardsPlugin.java:[21,36] package net.minecraft.server.v1_8_R3 does not exist
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/BetterShardsPlugin.java:[22,36] package net.minecraft.server.v1_8_R3 does not exist
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/BetterShardsPlugin.java:[24,29] package org.apache.commons.io does not exist
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/BetterShardsPlugin.java:[28,38] package org.bukkit.craftbukkit.v1_8_R3 does not exist
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/BetterShardsPlugin.java:[29,45] package org.bukkit.craftbukkit.v1_8_R3.entity does not exist
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/listeners/CombatTagListener.java:[5,36] package net.minecraft.server.v1_8_R3 does not exist
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/listeners/CombatTagListener.java:[6,36] package net.minecraft.server.v1_8_R3 does not exist
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/listeners/CombatTagListener.java:[7,36] package net.minecraft.server.v1_8_R3 does not exist
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/listeners/CombatTagListener.java:[8,36] package net.minecraft.server.v1_8_R3 does not exist
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/listeners/CombatTagListener.java:[15,45] package org.bukkit.craftbukkit.v1_8_R3.entity does not exist
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[15,45] package org.bukkit.craftbukkit.v1_8_R3.entity does not exist
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[21,36] package net.minecraft.server.v1_8_R3 does not exist
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[22,36] package net.minecraft.server.v1_8_R3 does not exist
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[23,36] package net.minecraft.server.v1_8_R3 does not exist
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[24,36] package net.minecraft.server.v1_8_R3 does not exist
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[25,36] package net.minecraft.server.v1_8_R3 does not exist
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[27,44] cannot find symbol
[ERROR] symbol: class ServerNBTManager
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[42,26] cannot find symbol
[ERROR] symbol:   class EntityHuman
[ERROR] location: class vg.civcraft.mc.bettershards.misc.CustomWorldNBTStorage
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[67,36] cannot find symbol
[ERROR] symbol:   class EntityHuman
[ERROR] location: class vg.civcraft.mc.bettershards.misc.CustomWorldNBTStorage
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[67,16] cannot find symbol
[ERROR] symbol:   class NBTTagCompound
[ERROR] location: class vg.civcraft.mc.bettershards.misc.CustomWorldNBTStorage
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[106,16] cannot find symbol
[ERROR] symbol:   class NBTTagCompound
[ERROR] location: class vg.civcraft.mc.bettershards.misc.CustomWorldNBTStorage
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[161,37] cannot find symbol
[ERROR] symbol:   class NBTTagCompound
[ERROR] location: class vg.civcraft.mc.bettershards.misc.CustomWorldNBTStorage
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[225,35] cannot find symbol
[ERROR] symbol:   class NBTTagCompound
[ERROR] location: class vg.civcraft.mc.bettershards.misc.CustomWorldNBTStorage
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/BetterShardsPlugin.java:[172,67] cannot find symbol
[ERROR] symbol:   class CraftPlayer
[ERROR] location: class vg.civcraft.mc.bettershards.BetterShardsPlugin
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/BetterShardsPlugin.java:[225,25] cannot find symbol
[ERROR] symbol:   class WorldServer
[ERROR] location: class vg.civcraft.mc.bettershards.BetterShardsPlugin
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/BetterShardsPlugin.java:[225,50] cannot find symbol
[ERROR] symbol:   class CraftWorld
[ERROR] location: class vg.civcraft.mc.bettershards.BetterShardsPlugin
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/BetterShardsPlugin.java:[228,73] package net.minecraft.server.v1_8_R3 does not exist
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/BetterShardsPlugin.java:[231,33] cannot find symbol
[ERROR] symbol:   class IDataManager
[ERROR] location: class vg.civcraft.mc.bettershards.BetterShardsPlugin
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/BetterShardsPlugin.java:[234,33] cannot find symbol
[ERROR] symbol:   class WorldNBTStorage
[ERROR] location: class vg.civcraft.mc.bettershards.BetterShardsPlugin
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/BetterShardsPlugin.java:[234,64] cannot find symbol
[ERROR] symbol:   class WorldNBTStorage
[ERROR] location: class vg.civcraft.mc.bettershards.BetterShardsPlugin
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/BetterShardsPlugin.java:[254,33] cannot find symbol
[ERROR] symbol:   variable MinecraftServer
[ERROR] location: class vg.civcraft.mc.bettershards.BetterShardsPlugin
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/BetterShardsPlugin.java:[297,25] cannot find symbol
[ERROR] symbol:   class WorldServer
[ERROR] location: class vg.civcraft.mc.bettershards.BetterShardsPlugin
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/BetterShardsPlugin.java:[297,50] cannot find symbol
[ERROR] symbol:   class CraftWorld
[ERROR] location: class vg.civcraft.mc.bettershards.BetterShardsPlugin
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/BetterShardsPlugin.java:[298,25] cannot find symbol
[ERROR] symbol:   class IDataManager
[ERROR] location: class vg.civcraft.mc.bettershards.BetterShardsPlugin
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/BetterShardsPlugin.java:[309,54] cannot find symbol
[ERROR] symbol:   variable IOUtils
[ERROR] location: class vg.civcraft.mc.bettershards.BetterShardsPlugin
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/listeners/CombatTagListener.java:[40,17] cannot find symbol
[ERROR] symbol:   class EntityPlayer
[ERROR] location: class vg.civcraft.mc.bettershards.listeners.CombatTagListener
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/listeners/CombatTagListener.java:[40,41] cannot find symbol
[ERROR] symbol:   class CraftPlayer
[ERROR] location: class vg.civcraft.mc.bettershards.listeners.CombatTagListener
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/listeners/CombatTagListener.java:[51,9] cannot find symbol
[ERROR] symbol:   class NBTTagCompound
[ERROR] location: class vg.civcraft.mc.bettershards.listeners.CombatTagListener
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/listeners/CombatTagListener.java:[57,34] cannot find symbol
[ERROR] symbol:   class FoodMetaData
[ERROR] location: class vg.civcraft.mc.bettershards.listeners.CombatTagListener
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/listeners/CombatTagListener.java:[74,62] cannot find symbol
[ERROR] symbol:   class NBTTagList
[ERROR] location: class vg.civcraft.mc.bettershards.listeners.CombatTagListener
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/listeners/CombatTagListener.java:[74,45] cannot find symbol
[ERROR] symbol:   variable inventory
[ERROR] location: variable npcPlayer of type net.minelink.ctplus.compat.v1_8_R3.NpcPlayer
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[41,9] method does not override or implement a method from a supertype
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[44,25] cannot find symbol
[ERROR] symbol:   class NBTTagCompound
[ERROR] location: class vg.civcraft.mc.bettershards.misc.CustomWorldNBTStorage
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[44,61] cannot find symbol
[ERROR] symbol:   class NBTTagCompound
[ERROR] location: class vg.civcraft.mc.bettershards.misc.CustomWorldNBTStorage
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[49,25] cannot find symbol
[ERROR] symbol:   variable NBTCompressedStreamTools
[ERROR] location: class vg.civcraft.mc.bettershards.misc.CustomWorldNBTStorage
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[66,9] method does not override or implement a method from a supertype
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[68,17] cannot find symbol
[ERROR] symbol:   class NBTTagCompound
[ERROR] location: class vg.civcraft.mc.bettershards.misc.CustomWorldNBTStorage
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[76,42] cannot find symbol
[ERROR] symbol:   variable NBTCompressedStreamTools
[ERROR] location: class vg.civcraft.mc.bettershards.misc.CustomWorldNBTStorage
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[88,53] cannot find symbol
[ERROR] symbol:   class EntityPlayer
[ERROR] location: class vg.civcraft.mc.bettershards.misc.CustomWorldNBTStorage
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[89,33] cannot find symbol
[ERROR] symbol:   class CraftPlayer
[ERROR] location: class vg.civcraft.mc.bettershards.misc.CustomWorldNBTStorage
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[89,55] cannot find symbol
[ERROR] symbol:   class CraftPlayer
[ERROR] location: class vg.civcraft.mc.bettershards.misc.CustomWorldNBTStorage
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[105,9] method does not override or implement a method from a supertype
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[112,25] cannot find symbol
[ERROR] symbol:   class NBTTagCompound
[ERROR] location: class vg.civcraft.mc.bettershards.misc.CustomWorldNBTStorage
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[112,57] cannot find symbol
[ERROR] symbol:   variable NBTCompressedStreamTools
[ERROR] location: class vg.civcraft.mc.bettershards.misc.CustomWorldNBTStorage
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[127,17] cannot find symbol
[ERROR] symbol:   class CraftPlayer
[ERROR] location: class vg.civcraft.mc.bettershards.misc.CustomWorldNBTStorage
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[127,40] cannot find symbol
[ERROR] symbol:   class CraftPlayer
[ERROR] location: class vg.civcraft.mc.bettershards.misc.CustomWorldNBTStorage
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[128,17] cannot find symbol
[ERROR] symbol:   class NBTTagCompound
[ERROR] location: class vg.civcraft.mc.bettershards.misc.CustomWorldNBTStorage
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[131,42] cannot find symbol
[ERROR] symbol:   variable NBTCompressedStreamTools
[ERROR] location: class vg.civcraft.mc.bettershards.misc.CustomWorldNBTStorage
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[144,17] cannot find symbol
[ERROR] symbol:   class CraftPlayer
[ERROR] location: class vg.civcraft.mc.bettershards.misc.CustomWorldNBTStorage
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[144,40] cannot find symbol
[ERROR] symbol:   class CraftPlayer
[ERROR] location: class vg.civcraft.mc.bettershards.misc.CustomWorldNBTStorage
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[145,17] cannot find symbol
[ERROR] symbol:   class NBTTagCompound
[ERROR] location: class vg.civcraft.mc.bettershards.misc.CustomWorldNBTStorage
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[145,53] cannot find symbol
[ERROR] symbol:   class NBTTagCompound
[ERROR] location: class vg.civcraft.mc.bettershards.misc.CustomWorldNBTStorage
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[151,25] cannot find symbol
[ERROR] symbol:   variable NBTCompressedStreamTools
[ERROR] location: class vg.civcraft.mc.bettershards.misc.CustomWorldNBTStorage
[ERROR] /C:/Users/Christian/Documents/MinecraftDev/BetterShards/src/vg/civcraft/mc/bettershards/misc/CustomWorldNBTStorage.java:[165,25] cannot find symbol
[ERROR] symbol:   variable NBTCompressedStreamTools
[ERROR] location: class vg.civcraft.mc.bettershards.misc.CustomWorldNBTStorage
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

### CODE REVIEW

**Comment by rourke750** [comment]
Yea, you'd have difficulty compiling this cause it needs spigot source not spigot api.

**Comment by rourke750** [comment]
@Scuwr You forgot to do the line before as well for getdbversion.

**Comment by ProgrammerDan** [comment]
@Scuwr download BuildTools.jar from spigot, build locally, and install the resulting spigot jar into your local maven repository using maven's install:install-file objective.

**Comment by Scuwr** [comment]
@ProgrammerDan I've already built BuildTools.jar. How exactly do I include it in the maven repo?

**Comment by rourke750** [comment]
Change the maven repo locally to spigot as artifact and 1.8.7 as version.

**Comment by Scuwr** [comment]
So are we intending to stick with 1.8.7? I have been compiling with 1.8.8 this whole time. (Also it worked! :+1: )

**Comment by ProgrammerDan** [comment]
@rourke750 pretty sure erocs been building 1.8.8.

**Comment by erocs** [comment]
We're on 1.8.8. As far as compiling is concerned, it doesn't matter for
anything on Jenkins.

**Comment by erocs** [comment]
Also, I don't believe Jenkins actually has a "1.8.8" version of spigot
registered in maven. We should probably do that and remove all the older
spigot versions.

**Comment by rourke750** [comment]
Nms didn't change between 1.8.7 and 1.8.8. @erocs pls don't touch
dependencies. That's a whole day in itself. Plug-ins that use Nms need to
be formated like namelayer.

**Comment by Scuwr** [comment]
Also, I have to say a big thank you to all of you for bearing with me while I've been trying to learn maven and these projects. I know how difficult it can be to teach someone completely unexposed to a new project or helpful tool, so I know I'm a huge thorn in your side right now. I try to do my best to google issues before I ask you too.

I do have another error in BetterShards that I can't solve for the life of me. BetterShardsPlugin.java is trying to lock some of the tables in mysql, but every time it tries to, the error returned is "NoSuchFieldException: sessonLock" is there something else I need to configure with mysql?

**Comment by rourke750** [comment]
Nope, just update to the newest spigot.

**Comment by Scuwr** [comment]
I'm using spigot-1.8.8.jar, I thought that was the newest one?

http://getspigot.org/jenkins/job/Spigot/

Last build is from 2 months ago.

**Comment by rourke750** [comment]
Rebuild by using the latest buildtools and use that jar.

**Comment by rourke750** [comment]
Also that sight isn't official.

**Comment by Scuwr** [comment]
Okay, so I retried it all with Build 46 from https://hub.spigotmc.org/jenkins/job/BuildTools/ and linked all of Spigot and Bukkit to maven.

```
java -jar BuildTools.jar --rev 1.8.8   

mvn install:install-file -Dfile=./spigot/spigot-1.8.8.jar -DgroupId=org.spigotmc -DartifactId=spigot -Dversion=1.8.8 -Dpackaging=jar -DpomFile=./spigot/spigot-pom.xml

mvn install:install-file -Dfile=./spigot/craftbukkit-1.8.8.jar -DgroupId=org.bukkit -DartifactId=craftbukkit -Dversion=1.8.8 -Dpackaging=jar -DpomFile=./spigot/craftbukkit-pom.xml
```

BuildTools ran without errors.
mvn install ran without errors.
BetterShards compiles without errors.

I still receive the same error: NoSuchFieldException: sessonLock when running the server locally.

```
[19:14:03 INFO]: [BetterShards] Enabling BetterShards v1.3.48
[19:14:03 INFO]: [BetterShardsPlugin] Main Plugin Events and Config Command registered
[19:14:03 INFO]: [BetterShards] Connected to database!
[19:14:03 WARN]: java.lang.NoSuchFieldException: sessionLock
[19:14:03 WARN]:        at java.lang.Class.getDeclaredField(Unknown Source)
[19:14:03 WARN]:        at vg.civcraft.mc.bettershards.BetterShardsPlugin.setWorldNBTStorage(BetterShardsPlugin.java:235)
[19:14:03 WARN]:        at vg.civcraft.mc.bettershards.BetterShardsPlugin.onEnable(BetterShardsPlugin.java:88)
[19:14:03 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[19:14:03 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[19:14:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[19:14:03 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[19:14:03 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[19:14:03 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[19:14:03 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[19:14:03 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[19:14:03 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[19:14:03 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[19:14:03 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:14:03 WARN]: java.lang.NoSuchFieldException: sessionLock
[19:14:03 WARN]:        at java.lang.Class.getDeclaredField(Unknown Source)
[19:14:03 WARN]:        at vg.civcraft.mc.bettershards.BetterShardsPlugin.setWorldNBTStorage(BetterShardsPlugin.java:235)
[19:14:03 WARN]:        at vg.civcraft.mc.bettershards.BetterShardsPlugin.onEnable(BetterShardsPlugin.java:88)
[19:14:03 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[19:14:03 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[19:14:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[19:14:03 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[19:14:03 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[19:14:03 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[19:14:03 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[19:14:03 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[19:14:03 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[19:14:03 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[19:14:03 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:14:03 WARN]: java.lang.NoSuchFieldException: sessionLock
[19:14:03 WARN]:        at java.lang.Class.getDeclaredField(Unknown Source)
[19:14:03 WARN]:        at vg.civcraft.mc.bettershards.BetterShardsPlugin.setWorldNBTStorage(BetterShardsPlugin.java:235)
[19:14:03 WARN]:        at vg.civcraft.mc.bettershards.BetterShardsPlugin.onEnable(BetterShardsPlugin.java:88)
[19:14:03 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[19:14:03 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[19:14:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[19:14:03 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[19:14:03 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[19:14:03 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[19:14:03 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[19:14:03 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[19:14:03 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[19:14:03 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[19:14:03 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:14:03 INFO]: [Citadel] Enabling Citadel v3.4.35
[19:14:03 INFO]: [Citadel] Connected to database!
[19:14:03 INFO]: [Citadel] [Citadel] The total time it took Citadel to update was 0 seconds.
[19:14:03 INFO]: Server permissions file permissions.yml is empty, ignoring it
[19:14:03 INFO]: Done (1.958s)! For help, type "help" or "?"
```

**Comment by rourke750** [comment]
I'll look when I get the chance.

**Comment by erocs** [comment]
What jar does Jenkins use, ours or public?

**Comment by rourke750** [comment]
@Scuwr When running the server are you using the newest spigot just produced?

**Comment by rourke750** [comment]
@erocs public.

**Comment by Scuwr** [comment]
Yes, my instance of the mc-server is Spigot-1.8.8.jar renamed and it is a copy of the one I just built an hour ago.

**Comment by rourke750** [comment]
@Scuwr Besides that error does the console spam anything?

**Comment by Scuwr** [comment]
No spamming. But I haven't logged into the server yet. I'll log in and run around a bit and tell you if I see any more errors.

**Comment by rourke750** [comment]
na, that wouldnt be the issue.  Alright if you want to just quickly fix it https://github.com/Civcraft/BetterShards/blob/master/src/vg/civcraft/mc/bettershards/BetterShardsPlugin.java#L234 from there to 249 just comment that out.

**Comment by rourke750** [comment]
@Scuwr actually wait a sec.

**Comment by Scuwr** [comment]
So does that mean that Spigot no longer locks the file?

**Comment by erocs** [comment]
Rourke stepped on something I customized.

**Comment by rourke750** [comment]
Erocs stepped on something I was stepping on to make our mysql inventories work, so I stepped on erocs.

**Comment by rourke750** [comment]
Anyways, I'll fix this later tonight.  Have some other stuff need to do first.

**Pull request merged**
